FROM node:20-alpine

WORKDIR /app

# Installer dépendances
COPY package*.json ./
RUN npm ci

EXPOSE 3000
ENV NODE_ENV=development

# Vite a besoin du flag --host pour fonctionner dans Docker
CMD ["npm", "run", "dev", "--", "--host"]
